// =============================================================================
// fp16_recip.v  —  Combinational fp16 reciprocal via mantissa LUT
// =============================================================================
// Computes result = 1 / a for fp16 values.
//
// Approach:
//   - Sign of output = sign of input (1/(-x) = -(1/x))
//   - Mantissa via 1024-entry LUT indexed by input mantissa
//   - Exponent computed arithmetically:
//       output_biased_exp = 2*BIAS - input_biased_exp - (m != 0 ? 1 : 0)
//                         = 30 - e - (m != 0 ? 1 : 0)
//     The -1 accounts for normalizing 1/(1.m) from (0.5, 1.0) into [1.0, 2.0).
//     When m == 0, the input is exactly 1.0 * 2^k and the reciprocal is
//     exactly 1.0 * 2^-k, no normalization needed.
//
// Special cases:
//   - Input is zero (FTZ-treated)  -> output is signed infinity
//   - Input is infinity             -> output is signed zero
//   - Input is denormal             -> treated as zero, output is signed inf
//
// LUT contents (`recip_lut.mem`) are generated by gen_recip_lut.py.
// =============================================================================

`timescale 1ns / 1ps
module fp16_recip (
    input  wire [15:0] a,
    output wire [15:0] result
);

    // -------------------------------------------------------------------------
    // Field extraction
    // -------------------------------------------------------------------------
    wire        sign_a = a[15];
    wire [4:0]  exp_a  = a[14:10];
    wire [9:0]  man_a  = a[9:0];

    wire is_zero_or_denorm = (exp_a == 5'd0);            // FTZ: denorm == 0
    wire is_inf            = (exp_a == 5'd31) && (man_a == 10'd0);
    wire mantissa_nonzero  = (man_a != 10'd0);

    // -------------------------------------------------------------------------
    // Mantissa LUT — 1024 entries, 10 bits each. Inferred as ROM by Vivado
    // from the $readmemh initialization.
    // -------------------------------------------------------------------------
    reg [9:0] recip_lut [0:1023];
    initial $readmemh("recip_lut.mem", recip_lut);

    wire [9:0] mantissa_lookup = recip_lut[man_a];

    // -------------------------------------------------------------------------
    // Exponent transformation:
    //   new_exp = 30 - exp_a - (mantissa_nonzero ? 1 : 0)
    //
    // Sanity check: a = 1.0 (exp_a = 15, man_a = 0)
    //               new_exp = 30 - 15 - 0 = 15 = bias of 1.0  OK
    //               a = 2.0 (exp_a = 16, man_a = 0)
    //               new_exp = 30 - 16 - 0 = 14 = bias of 0.5  OK
    //               a = 1.5 (exp_a = 15, man_a = 0x200, value = 1.5)
    //               1/1.5 ~= 0.666..., fp16 bias = 14
    //               new_exp = 30 - 15 - 1 = 14  OK
    // -------------------------------------------------------------------------
    wire signed [6:0] new_exp = 7'sd30 - $signed({2'b0, exp_a})
                              - (mantissa_nonzero ? 7'sd1 : 7'sd0);

    // -------------------------------------------------------------------------
    // Over/underflow on the new exponent. Reciprocals of very small numbers
    // overflow; reciprocals of very large numbers underflow.
    // -------------------------------------------------------------------------
    wire overflow  = (new_exp > 7'sd30);
    wire underflow = (new_exp < 7'sd1);

    // -------------------------------------------------------------------------
    // Final assembly
    //   - input zero/denorm -> output is signed infinity
    //   - input inf         -> output is signed zero
    //   - overflow          -> signed infinity
    //   - underflow         -> flush to zero
    // -------------------------------------------------------------------------
    assign result =
        is_zero_or_denorm ? {sign_a, 5'd31, 10'd0}                       :
        is_inf            ? {sign_a, 5'd0,  10'd0}                       :
        overflow          ? {sign_a, 5'd31, 10'd0}                       :
        underflow         ? {sign_a, 5'd0,  10'd0}                       :
                            {sign_a, new_exp[4:0], mantissa_lookup};

endmodule
