// =============================================================================
// MVP_matrix_maker.v  —  Per-frame MVP matrix builder
// =============================================================================
// On each `start` pulse:
//   1. Latch the current rotation speeds, advance the internal angle
//      registers by them (wrap-around is automatic in 8 bits).
//   2. Build rotation matrices Rx and Ry from the sin/cos LUT.
//   3. Drive mat_mul to compute M = Ry * Rx.
//   4. Capture the 16 result elements into an internal "M" register array.
//   5. Drive mat_mul a second time to compute MVP = PV * M, where PV is a
//      hardcoded constant matrix from the camera setup.
//   6. As MVP elements stream out, write them to Transform RAM via the
//      ram_* interface.
//   7. Assert `done`.
//
// MVP_matrix_maker does NOT instantiate mat_mul itself — it drives the
// mat_mul interface, which the top level muxes between MVP_matrix_maker and
// the vertex-batch streaming logic.
// =============================================================================


module MVP_matrix_maker (
    input  wire         clk,
    input  wire         rst,
    input  wire         start,             // FSM pulse: begin one MVP build

    input  wire signed [7:0]  speed_x,     // added to angle_x on start
    input  wire signed [7:0]  speed_y,     // added to angle_y on start

    // mat_mul interface (top level muxes this with the vertex-batch path)
    output reg          mat_rst,
    output reg  [7:0]   mat_N,
    output reg  [7:0]   mat_M,
    output reg  [7:0]   mat_P,
    output reg          mat_write_a,
    output reg  [15:0]  mat_data_a,
    output reg          mat_loaded_a,
    output reg          mat_write_b,
    output reg  [15:0]  mat_data_b,
    output reg          mat_loaded_b,
    input  wire [15:0]  mat_data_out,
    input  wire         mat_out_valid,
    input  wire         mat_busy,

    // Transform RAM write interface (the section that holds the MVP)
    output reg          ram_wen,
    output reg  [3:0]   ram_addr,          // 16 words at the MVP base
    output reg  [15:0]  ram_din,

    output reg          done
);

    // -------------------------------------------------------------------------
    // P x V constant matrix (camera fixed: CAM_DIST=400, NEAR=10, FAR=1000,
    // FOV=90deg, aspect=4:3). Row-major. Generated by gen_pv_matrix.py.
    // -------------------------------------------------------------------------
    reg [15:0] PV [0:15];
    initial begin
        PV[ 0] = 16'h3a00;  // +0.750000
        PV[ 1] = 16'h0000;  // +0.000000
        PV[ 2] = 16'h0000;  // +0.000000
        PV[ 3] = 16'h0000;  // +0.000000
        PV[ 4] = 16'h0000;  // +0.000000
        PV[ 5] = 16'h3c00;  // +1.000000
        PV[ 6] = 16'h0000;  // +0.000000
        PV[ 7] = 16'h0000;  // +0.000000
        PV[ 8] = 16'h0000;  // +0.000000
        PV[ 9] = 16'h0000;  // +0.000000
        PV[10] = 16'hbc15;  // -1.020508
        PV[11] = 16'h5e10;  // +388.000000
        PV[12] = 16'h0000;  // +0.000000
        PV[13] = 16'h0000;  // +0.000000
        PV[14] = 16'hbc00;  // -1.000000
        PV[15] = 16'h5e40;  // +400.000000
    end

    // -------------------------------------------------------------------------
    // Constants used in rotation matrices
    // -------------------------------------------------------------------------
    localparam [15:0] FP16_ZERO = 16'h0000;
    localparam [15:0] FP16_ONE  = 16'h3c00;

    // -------------------------------------------------------------------------
    // Angle registers and sin/cos lookups
    // -------------------------------------------------------------------------
    reg [7:0] angle_x;
    reg [7:0] angle_y;

    wire [15:0] sin_x, cos_x, sin_y, cos_y;
    sincos_lut u_sc_x (.angle(angle_x), .sin_val(sin_x), .cos_val(cos_x));
    sincos_lut u_sc_y (.angle(angle_y), .sin_val(sin_y), .cos_val(cos_y));

    // -------------------------------------------------------------------------
    // Build Rx and Ry as 16-element fp16 arrays (row-major).
    //
    //   Rx = | 1     0       0      0 |
    //        | 0   cos_x  -sin_x    0 |
    //        | 0   sin_x   cos_x    0 |
    //        | 0     0       0      1 |
    //
    //   Ry = | cos_y    0   sin_y   0 |
    //        |   0      1     0     0 |
    //        |-sin_y    0   cos_y   0 |
    //        |   0      0     0     1 |
    //
    // We compute negations of sin_x / sin_y by flipping the fp16 sign bit.
    // -------------------------------------------------------------------------
    wire [15:0] neg_sin_x = {~sin_x[15], sin_x[14:0]};
    wire [15:0] neg_sin_y = {~sin_y[15], sin_y[14:0]};

    wire [15:0] Rx [0:15];
    wire [15:0] Ry [0:15];

    assign Rx[ 0] = FP16_ONE;  assign Rx[ 1] = FP16_ZERO; assign Rx[ 2] = FP16_ZERO;   assign Rx[ 3] = FP16_ZERO;
    assign Rx[ 4] = FP16_ZERO; assign Rx[ 5] = cos_x;     assign Rx[ 6] = neg_sin_x;   assign Rx[ 7] = FP16_ZERO;
    assign Rx[ 8] = FP16_ZERO; assign Rx[ 9] = sin_x;     assign Rx[10] = cos_x;       assign Rx[11] = FP16_ZERO;
    assign Rx[12] = FP16_ZERO; assign Rx[13] = FP16_ZERO; assign Rx[14] = FP16_ZERO;   assign Rx[15] = FP16_ONE;

    assign Ry[ 0] = cos_y;     assign Ry[ 1] = FP16_ZERO; assign Ry[ 2] = sin_y;       assign Ry[ 3] = FP16_ZERO;
    assign Ry[ 4] = FP16_ZERO; assign Ry[ 5] = FP16_ONE;  assign Ry[ 6] = FP16_ZERO;   assign Ry[ 7] = FP16_ZERO;
    assign Ry[ 8] = neg_sin_y; assign Ry[ 9] = FP16_ZERO; assign Ry[10] = cos_y;       assign Ry[11] = FP16_ZERO;
    assign Ry[12] = FP16_ZERO; assign Ry[13] = FP16_ZERO; assign Ry[14] = FP16_ZERO;   assign Ry[15] = FP16_ONE;

    // -------------------------------------------------------------------------
    // Internal M = Ry * Rx storage, filled by the first mat_mul pass
    // -------------------------------------------------------------------------
    reg [15:0] M_storage [0:15];

    // -------------------------------------------------------------------------
    // FSM
    //
    //   IDLE        — quiescent. On `start`, update angles, go LOAD_MUL1.
    //   LOAD_MUL1   — stream Ry into A and Rx into B (16 cycles).
    //   RUN_MUL1    — assert loaded; collect result elements into M_storage
    //                 as out_valid pulses arrive (16 elements).
    //   RST_MUL     — assert mat_rst for one cycle to clear mat_mul between
    //                 the two multiplies (so its FSM returns to IDLE).
    //   LOAD_MUL2   — stream PV into A and M into B (16 cycles).
    //   RUN_MUL2    — assert loaded; as out_valid pulses arrive, write each
    //                 element to Transform RAM.
    //   DONE        — pulse done, return to IDLE.
    // -------------------------------------------------------------------------
    localparam IDLE      = 4'd0;
    localparam LOAD_MUL1 = 4'd1;
    localparam RUN_MUL1  = 4'd2;
    localparam RST_MUL   = 4'd3;
    localparam LOAD_MUL2 = 4'd4;
    localparam RUN_MUL2  = 4'd5;
    localparam DONE_S    = 4'd6;
    reg [3:0] state;

    // Counters
    reg [4:0] stream_idx;       // 0..15 during loading
    reg [4:0] collect_idx;      // 0..15 during result collection

    // =========================================================================
    // FSM and datapath
    // =========================================================================
    always @(posedge clk) begin
        if (rst) begin
            state         <= IDLE;
            angle_x       <= 8'd0;
            angle_y       <= 8'd0;
            stream_idx    <= 0;
            collect_idx   <= 0;
            done          <= 1'b0;
            mat_rst       <= 1'b0;
            mat_write_a   <= 1'b0;
            mat_write_b   <= 1'b0;
            mat_loaded_a  <= 1'b0;
            mat_loaded_b  <= 1'b0;
            mat_N <= 4; mat_M <= 4; mat_P <= 4;
            ram_wen       <= 1'b0;
        end else begin
            // Default deassertions (overridden by states below)
            done         <= 1'b0;
            mat_rst      <= 1'b0;
            mat_write_a  <= 1'b0;
            mat_write_b  <= 1'b0;
            mat_loaded_a <= 1'b0;
            mat_loaded_b <= 1'b0;
            ram_wen      <= 1'b0;

            case (state)

            // -----------------------------------------------------------------
            // IDLE — wait for start, then advance angles and begin first mul.
            // -----------------------------------------------------------------
            IDLE: if (start) begin
                angle_x    <= angle_x + speed_x;
                angle_y    <= angle_y + speed_y;
                stream_idx <= 0;
                mat_N <= 4; mat_M <= 4; mat_P <= 4;
                state <= LOAD_MUL1;
            end

            // -----------------------------------------------------------------
            // LOAD_MUL1 — stream Ry as A, Rx as B, one element per cycle.
            // -----------------------------------------------------------------
            LOAD_MUL1: begin
                mat_write_a <= 1'b1;
                mat_write_b <= 1'b1;
                mat_data_a  <= Ry[stream_idx];
                mat_data_b  <= Rx[stream_idx];
                if (stream_idx == 5'd15) begin
                    stream_idx  <= 0;
                    collect_idx <= 0;
                    state       <= RUN_MUL1;
                end else begin
                    stream_idx <= stream_idx + 1;
                end
            end

            // -----------------------------------------------------------------
            // RUN_MUL1 — assert loaded flags on entry; collect mat_data_out
            // into M_storage when mat_out_valid pulses.
            // -----------------------------------------------------------------
            RUN_MUL1: begin
                // Pulse loaded flags on the first cycle of RUN_MUL1
                if (collect_idx == 0 && !mat_out_valid) begin
                    mat_loaded_a <= 1'b1;
                    mat_loaded_b <= 1'b1;
                end

                if (mat_out_valid) begin
                    M_storage[collect_idx] <= mat_data_out;
                    if (collect_idx == 5'd15) begin
                        collect_idx <= 0;
                        state       <= RST_MUL;
                    end else begin
                        collect_idx <= collect_idx + 1;
                    end
                end
            end

            // -----------------------------------------------------------------
            // RST_MUL — pulse mat_rst for one cycle to bring mat_mul back to
            // IDLE before the second multiply.
            // -----------------------------------------------------------------
            RST_MUL: begin
                mat_rst   <= 1'b1;
                stream_idx <= 0;
                state      <= LOAD_MUL2;
            end

            // -----------------------------------------------------------------
            // LOAD_MUL2 — stream PV as A, M_storage as B.
            // -----------------------------------------------------------------
            LOAD_MUL2: begin
                mat_write_a <= 1'b1;
                mat_write_b <= 1'b1;
                mat_data_a  <= PV[stream_idx];
                mat_data_b  <= M_storage[stream_idx];
                if (stream_idx == 5'd15) begin
                    stream_idx  <= 0;
                    collect_idx <= 0;
                    state       <= RUN_MUL2;
                end else begin
                    stream_idx <= stream_idx + 1;
                end
            end

            // -----------------------------------------------------------------
            // RUN_MUL2 — assert loaded; write each output element to
            // Transform RAM as it arrives.
            // -----------------------------------------------------------------
            RUN_MUL2: begin
                if (collect_idx == 0 && !mat_out_valid) begin
                    mat_loaded_a <= 1'b1;
                    mat_loaded_b <= 1'b1;
                end

                if (mat_out_valid) begin
                    ram_wen  <= 1'b1;
                    ram_addr <= collect_idx[3:0];
                    ram_din  <= mat_data_out;
                    if (collect_idx == 5'd15) begin
                        collect_idx <= 0;
                        state       <= DONE_S;
                    end else begin
                        collect_idx <= collect_idx + 1;
                    end
                end
            end

            // -----------------------------------------------------------------
            // DONE — one-cycle done pulse; back to IDLE.
            // -----------------------------------------------------------------
            DONE_S: begin
                done  <= 1'b1;
                state <= IDLE;
            end

            default: state <= IDLE;
            endcase
        end
    end

endmodule