// =============================================================================
// sincos_lut.v  —  Combinational fp16 sine/cosine lookup
// =============================================================================
// 8-bit angle index in, fp16 sine and cosine out.
//
// Index encoding (1 LSB = 360/256 deg = 1.40625 deg):
//   0   -> 0 rad         (sin 0,  cos 1)
//   64  -> pi/2          (sin 1,  cos 0)
//   128 -> pi            (sin 0,  cos -1)
//   192 -> 3*pi/2        (sin -1, cos 0)
//
// Values come from sin_lut.mem and cos_lut.mem, generated by
// gen_sincos_lut.py and loaded at elaboration via $readmemh. Vivado will
// infer these as ROMs (distributed or block, its choice — both are fine
// at this size).
// =============================================================================

`timescale 1ns / 1ps
module sincos_lut (
    input  wire [7:0]  angle,
    output wire [15:0] sin_val,
    output wire [15:0] cos_val
);

    reg [15:0] sin_rom [0:255];
    reg [15:0] cos_rom [0:255];

    initial begin
        $readmemh("sin_lut.mem", sin_rom);
        $readmemh("cos_lut.mem", cos_rom);
    end

    assign sin_val = sin_rom[angle];
    assign cos_val = cos_rom[angle];

endmodule
