# =============================================================================
# Makefile — FPGA wireframe renderer
# =============================================================================
# Usage:
#   make                 — same as `make test`
#   make test            — build and run every testbench
#   make test-<name>     — build and run one testbench, e.g. `make test-fp16_mul`
#   make wave-<name>     — same as test-<name>, then open the VCD in GTKWave
#   make lint            — elaborate every rtl/ module (catches syntax errors)
#   make hex             — regenerate the .hex LUT files via the Python scripts
#   make clean           — remove build/, waves/, and any stale .vcd files
#
# Layout assumed:
#   rtl/        synthesizable modules (.v)
#   tb/         testbenches (*_tb.v)
#   scripts/    Python helpers (gen_*.py, etc.)
#   data/       .hex LUT files (committed; read by $readmemh)
#   build/      iverilog output binaries (gitignored)
#   waves/      .vcd dump files (gitignored)
#   docs/       markdown + diagrams
# =============================================================================

# ----- Tool config -----------------------------------------------------------

IVERILOG     := iverilog
VVP          := vvp
GTKWAVE      := gtkwave
# On macOS, the Homebrew `gtkwave` binary is a Perl shim that breaks on
# recent macOS Perl. If `make wave-*` errors out with "Can't locate Switch.pm",
# either install the Perl module (`cpan -i Switch`) or set GTKWAVE_CMD to
# `open -a gtkwave` to launch the .app directly:
#     make wave-foo GTKWAVE_CMD="open -a gtkwave"
GTKWAVE_CMD  := $(GTKWAVE)
PYTHON       := python3

# Include paths handed to iverilog. Both rtl/ and data/ so $readmemh can find
# the .hex files via relative path.
IVERILOG_FLAGS := -g2012 -Wall -Irtl -Idata

# ----- File discovery --------------------------------------------------------

RTL_SRCS  := $(wildcard rtl/*.v)
TB_SRCS   := $(wildcard tb/*_tb.v)
TB_NAMES  := $(notdir $(basename $(TB_SRCS)))      # e.g. "fp16_mul_tb"
TEST_NAMES := $(patsubst %_tb,%,$(TB_NAMES))       # e.g. "fp16_mul"

# Hex files generated by scripts/. List them explicitly so `make hex` knows
# what to regenerate.
HEX_FILES := data/recip_lut.hex

# ----- Phony targets ---------------------------------------------------------

.PHONY: all test lint hex clean help

# Keep intermediate build/*_tb files around — without this, GNU make treats
# them as implicit intermediates and deletes them after each run.
.SECONDARY:

all: test

help:
	@echo "Targets:"
	@echo "  make test            run every testbench"
	@echo "  make test-<name>     run one testbench"
	@echo "  make wave-<name>     run testbench, then open VCD in GTKWave"
	@echo "  make lint            elaborate every rtl/ module"
	@echo "  make hex             regenerate .hex LUT files"
	@echo "  make clean           remove build/ and waves/"
	@echo ""
	@echo "Available testbenches:"
	@for name in $(TEST_NAMES); do echo "  $$name"; done

# ----- Directories -----------------------------------------------------------

build:
	@mkdir -p build

waves:
	@mkdir -p waves

# ----- Hex file generation ---------------------------------------------------

hex: $(HEX_FILES)

data/recip_lut.hex: scripts/gen_recip_lut.py | data
	$(PYTHON) $< $@
data:
	@mkdir -p data

# ----- Per-testbench build + run ---------------------------------------------
#
# For testbench `foo_tb.v` in tb/, build to `build/foo_tb` from all rtl/*.v
# sources plus the testbench itself. We compile the WHOLE rtl/ tree every
# time — slower than tracking per-module dependencies, but reliable and
# fast enough for this project size.
#
# Hex files are an order-only prereq so they're built once but don't trigger
# unnecessary rebuilds.

build/%_tb: tb/%_tb.v $(RTL_SRCS) | build hex
	$(IVERILOG) $(IVERILOG_FLAGS) -o $@ $(RTL_SRCS) $<

# Run one testbench by name (e.g. `make test-fp16_mul`). Runs from the project
# root so $readmemh references like "data/recip_lut.hex" resolve correctly,
# and testbenches should $dumpfile("waves/<name>.vcd") to land VCDs in waves/.
test-%: build/%_tb | waves
	@echo "=== running $* ==="
	$(VVP) $<

# Open the resulting VCD in GTKWave (e.g. `make wave-fp16_mul`)
wave-%: test-%
	$(GTKWAVE_CMD) waves/$*_tb.vcd &

# Run all testbenches
test: $(addprefix test-,$(TEST_NAMES))

# ----- Lint: elaborate every rtl/ module without running simulation ----------

lint:
	@echo "=== linting rtl/ ==="
	$(IVERILOG) $(IVERILOG_FLAGS) -tnull -o /dev/null $(RTL_SRCS)

# ----- Cleanup ---------------------------------------------------------------

clean:
	rm -rf build/ waves/
	find . -name "*.vcd" -not -path "./waves/*" -delete